version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # 소스 코드 변경을 즉시 반영하기 위한 볼륨 마운트
      - ./db:/app/db # 로컬 DB 폴더를 컨테이너에 연결
      - ./music_library:/app/music_library # 로컬 음악 라이브러리를 컨테이너에 연결
    env_file:
      - .env    # .env 파일에서 환경 변수를 로드
